<?php
/**
 * Generated configuration file
 * Generated by: phpMyAdmin 5.2.1 setup script
 * Date: Tue, 12 Dec 2023 13:41:11 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: Local Server [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Local Server';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'admin';
$cfg['Servers'][$i]['password'] = 'Pass1234';
$cfg['Servers'][$i]['AllowRoot'] = false;

/* End of servers configuration */

$cfg['blowfish_secret'] = \sodium_hex2bin('44a99a0fb102ef6edc832de3edd0120e2ff0e55f91c548eae933130bfd40d0da');
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';

